### ISSUE TITLE
 IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by Fangfenghua** [seb-m/pyinotify#93] opened 2015-03-05 03:10 UTC
localhost tset.py ERROR [type:run] [pid:6822] [Thread-36] [test.py:56 run] file monitor process events got a exception, e=[Errno 9] Bad file descriptor, trace=Traceback (most recent call last):   File "/test.py", line 54, in run     notifier.read_events()   File "test.py", line 1239, in read_events     if fcntl.ioctl(self._fd, termios.FIONREAD, buf_, 1) == -1: IOError: [Errno 9] Bad file descriptor

**Comment by seb-m** [comment] 2015-03-05 07:42
Hard to figure out what the problem is here. This kind of error most probably either mean the socket has already been closed or the file descriptor is invalid.

**Comment by blueyed** [comment] 2015-03-16 20:24
This might also happen when closing the notifier twice, which I have a fix for already.

**Closed** 2015-06-04 13:42 UTC
