### ISSUE TITLE
Crash in help() / repr

### ISSUE THREAD

**Issue by terjeros** [seb-m/pyinotify#99] opened 2015-06-02 18:07 UTC
Python 2 and 3 versions crashes:

    >>> import pyinotify
    >>> help(pyinotify) 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.3/site.py", line 474, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib64/python3.3/pydoc.py", line 1789, in __call__
    self.help(request)
  File "/usr/lib64/python3.3/pydoc.py", line 1839, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib64/python3.3/pydoc.py", line 1575, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib64/python3.3/pydoc.py", line 1568, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib64/python3.3/pydoc.py", line 349, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/lib64/python3.3/pydoc.py", line 1143, in docmodule
    contents.append(self.docother(value, key, name, maxlen=70))
  File "/usr/lib64/python3.3/pydoc.py", line 1361, in docother
    repr = self.repr(object)
  File "/usr/lib64/python3.3/reprlib.py", line 54, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib64/python3.3/pydoc.py", line 1002, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/usr/lib/python3.3/site-packages/pyinotify.py", line 349, in __repr__
    return '<%s=%d>' % (self._attrname, self.get_val())
  File "/usr/lib/python3.3/site-packages/pyinotify.py", line 322, in get_val
    self._inotify_wrapper.str_errno())
OSError: [Errno 14] Errno=Bad address (EFAULT)
```

    >>> import pyinotify
    >>> help(pyinotify)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site.py", line 459, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib64/python2.7/pydoc.py", line 1745, in __call__
    self.help(request)
  File "/usr/lib64/python2.7/pydoc.py", line 1792, in help
    else: doc(request, 'Help on %s:')
  File "/usr/lib64/python2.7/pydoc.py", line 1529, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib64/python2.7/pydoc.py", line 1524, in render_doc
    return title % desc + '\n\n' + text.document(object, name)
  File "/usr/lib64/python2.7/pydoc.py", line 326, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/lib64/python2.7/pydoc.py", line 1112, in docmodule
    contents.append(self.docother(value, key, name, maxlen=70))
  File "/usr/lib64/python2.7/pydoc.py", line 1318, in docother
    repr = self.repr(object)
  File "/usr/lib64/python2.7/repr.py", line 24, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib64/python2.7/pydoc.py", line 967, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 361, in __repr__
    return '<%s=%d>' % (self._attrname, self.get_val())
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 334, in get_val
    self._inotify_wrapper.str_errno())
OSError: [Errno 38] Errno=Function not implemented (ENOSYS)

```

**Comment by seb-m** [comment] 2015-06-04 13:13
duplicate of #84

**Closed by seb-m** 2015-06-04 13:13 UTC
Labels: bug
